version: "1.0"
services:
  www:
    image: "d6cb6d73h/dokuwiki-www-alpine:latest"
    ports:
        - "8080:80"
    depends_on:
        - php
    volumes:
        - ../dokuwiki-2020-07-29/:/var/www/html
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
    links:
        - "php-fpm:pfp-fpm"
  php-fpm:
    image: "d6cb6d73h/dokuwiki-php-alpine:latest"
    volumes:
        - ../dokuwiki-2020-07-29/:/var/www/html
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: dnsrr
networks:
  default:
    name: Dokuwiki